name: ci

on:
  pull_request:
    branches: [main]

jobs:
  unit_test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: latest

      - name: Install dependencies
        run: bun i

      - name: Run tests
        run: bun run test --coverage

  style_test:
    name: Style Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: latest

      - name: Install dependencies
        run: bun i

      - name: Run prettier
        run: bun run format:check

      - name: Run lint
        run: bun run lint --max-warnings=0
